services:
  structurizr-lite:
    image: structurizr/lite
    ports:
      - 8081:8080
    volumes:
      - ./src:/usr/local/structurizr

  plantuml:
    image: plantuml/plantuml-server
    ports:
      - 8080:8080
