#!/bin/sh
FILE_TO_MONITOR="$1"
shift

"$@"
SHA=$(sha256sum "$FILE_TO_MONITOR")
DIR_TO_MONITOR=$(dirname "$FILE_TO_MONITOR")
inotifywait -m $DIR_TO_MONITOR |
while read -r directory events filename; do
    if [ "$directory$filename" != "$FILE_TO_MONITOR" ]; then
        continue
    fi
    NEW_SHA=$(sha256sum "$FILE_TO_MONITOR")
    if [ "$NEW_SHA" == "$SHA" ]; then
        continue
    fi
    echo $(date "+%Y-%m-%d %H:%M:%S") - "$@"
    "$@"
    SHA=$NEW_SHA
done
